### ISSUE TITLE
The ide has some problems in web

### ISSUE THREAD

**Issue by HendricksRichard** [lark-parser/ide#6]
these days, I can't use online IDE，and the given  information is **Please wait, loading... Loading Pyodide**

**Comment by erezsh** [comment]
It works for me on both Firefox and Chrome. You'll have to give me more details.

**Comment by HendricksRichard** [comment]
Thank you for your apply!

I've tested it on several machines with chrome and edge, but it does not work. It shows  **Loading Pyodide**, and parsing result cannot be displayed.
The same problem goes for my friends.

**Comment by HendricksRichard** [comment]
Thank you for your apply!

I've tested it on several machines with chrome and edge, but it does not work. It shows  **Loading Pyodide**, and parsing result cannot be displayed.
The same problem goes for my friends.

**Comment by MegaIng** [comment]
For me it succesfully loads Pyodide and works.

**Comment by erezsh** [comment]
@HendricksRichard Are you all trying to access it from the same network?

**Comment by HendricksRichard** [comment]
> @HendricksRichard Are you all trying to access it from the same network?

I have tried different network. Until now, I have tested four machines, both the same problem.
Is it because I am in China？

**Comment by erezsh** [comment]
That would be my guess. Looks like, somewhere along the way, one of the dependencies gets blocked from downloading. Sorry!

**Comment by HendricksRichard** [comment]
@erezsh Thank you for your attention! It helps me a lot!
